### ISSUE TITLE
请问这东西怎么用呀？

### ISSUE THREAD

**Issue by CX-330** [lNeverl/cidarenRestartTheProject#1]
xx英语老师留了好多任务。。python不太懂这些库，

**Comment by lNeverl** [comment]
我还没写完呢hhhhhhhhhhhhhhh

**Comment by CX-330** [comment]
28号xx英语老师留了8个任务，一个任务36个单词，我做一个任务一个半小时，今天还要留！！五月五号截至，太ex了

**Comment by lNeverl** [comment]
> 28号xx英语老师留了8个任务，一个任务36个单词，我做一个任务一个半小时，今天还要留！！

我看bilibili有一个可以做学习任务的  你可以先用那个 我这个到时候写出来应该是都能用的

**Comment by CX-330** [comment]
谢谢啦！我去康康。要是英语老师留的少我就自己做了，害

**Comment by lNeverl** [comment]
> 谢谢啦！我去康康。要是英语老师留的少我就自己做了，害

我写出来了  目前还在测试 有bug可以反馈

**Comment by CX-330** [comment]
棒！B站我发现有用fiddler抓的，还有有一个做出软件来开始搭建题库了，，，

**Comment by lNeverl** [comment]
> 棒！B站我发现有用的fiddler抓的，还有有一个做出软件来开始建造题库了，，，

嗯   有    我刚有个代码 写错了   马上更新

**Comment by CX-330** [comment]
clone下来了正准备安装库呢，，，python环境都在linux下，把编译器生成的程序也传一下呗？这样就不用安装库了

**Comment by lNeverl** [comment]
> clone下来了正准备安装库呢，，， python环境都在linux下，把编译器生成的程序也传一下呗？这样就不用安装库了

不用克隆 克隆下的没用了   在发行版中 或者点那个下载连接

**Comment by CX-330** [comment]
好哒~
