### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by 1578339936** [lNeverl/cidarenRestartTheProject#3]
经常性的闪退

**Comment by lNeverl** [comment]
> 经常性的闪退

对的 目前是这样  应为json中的文件在界面登录刷新题型切换等操作时导入一些奇怪的东西   有时间在修复吧

**Comment by lNeverl** [comment]
> 经常性的闪退

不对啊  这个已经优化过了啊 怎么还会闪退呢   ，你下次启动的时候，这样操作来打开软件
```

1.按win+r，在输入栏输入cmd，然后回车打开命令提示符，
2.把那个exe拖进命令提示符，回车，注意是点一下命令提示符在回车。
3.在闪退时候不要做任何操作，记录下当前的错误提示，同时记录下c/cdr文件夹下的responseBody.txt的内容。然后一起发给我。

```

**Comment by 1578339936** [comment]
错误提示
Traceback (most recent call last):
  File "cidaren.py", line 59, in <module>
  File "json\__init__.py", line 348, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[18072] Failed to execute script cidaren
文件内容
{"code":1,"msg":"处理成功！","data":{"task_type":2,"topic_mode":17,"stem":{"content":"verb 攻击；进攻","remark":null,"ph_us_url":null,"ph_en_url":null},"options":[{"content":"debate","remark":null,"answer":null,"answer_tag":0,"check_code":null,"sub_options":null},{"content":"structure","remark":null,"answer":null,"answer_tag":1,"check_code":null,"sub_options":null},{"content":"attack","remark":null,"answer":null,"answer_tag":2,"check_code":null,"sub_options":null},{"content":"rock","remark":null,"answer":null,"answer_tag":3,"check_code":null,"sub_options":null}],"answer_num":1,"chance_num":1,"topic_done_num":11,"topic_total":72,"tips":null,"task_id":10652029,"topic_code":"jFJ5fYVklpODYFKoeoprl2mYYmyEZFmXrKqamaCHkGdrjZZrZXCOY1xnaGdlaZKTbVyXZmlsaGluZmS9apRiaWJqYpDAwZNgkphxbGubY2NtaWplab8=","answer_state":1}}
这个内容倒是没有什么问题，跟抓到的对的上

**Comment by lNeverl** [comment]
> 错误提示
> Traceback (most recent call last):
> File "cidaren.py", line 59, in
> File "json__init__.py", line 348, in loads
> File "json\decoder.py", line 337, in decode
> File "json\decoder.py", line 355, in raw_decode
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> [18072] Failed to execute script cidaren
> 文件内容
> {"code":1,"msg":"处理成功！","data":{"task_type":2,"topic_mode":17,"stem":{"content":"verb 攻击；进攻","remark":null,"ph_us_url":null,"ph_en_url":null},"options":[{"content":"debate","remark":null,"answer":null,"answer_tag":0,"check_code":null,"sub_options":null},{"content":"structure","remark":null,"answer":null,"answer_tag":1,"check_code":null,"sub_options":null},{"content":"attack","remark":null,"answer":null,"answer_tag":2,"check_code":null,"sub_options":null},{"content":"rock","remark":null,"answer":null,"answer_tag":3,"check_code":null,"sub_options":null}],"answer_num":1,"chance_num":1,"topic_done_num":11,"topic_total":72,"tips":null,"task_id":10652029,"topic_code":"jFJ5fYVklpODYFKoeoprl2mYYmyEZFmXrKqamaCHkGdrjZZrZXCOY1xnaGdlaZKTbVyXZmlsaGluZmS9apRiaWJqYpDAwZNgkphxbGubY2NtaWplab8=","answer_state":1}}
> 这个内容倒是没有什么问题，跟抓到的对的上

这个问题修复了，还是闪退的话继续这样反馈就好了。马上上传4.0.2
