### ISSUE TITLE
是不是接口更新了，请作者更新一下吧

### ISSUE THREAD

**Issue by 1578339936** [lNeverl/cidarenRestartTheProject#4]
![2345截图20200506212309](https://user-images.githubusercontent.com/62222561/81182069-ede66600-8fdf-11ea-8ba1-7f767a793db0.png)
是不是接口更新了，请作者更新一下吧

**Comment by lNeverl** [comment]
> ![2345截图20200506212309](https://user-images.githubusercontent.com/62222561/81182069-ede66600-8fdf-11ea-8ba1-7f767a793db0.png)
> 是不是接口更新了，请作者更新一下吧

词达人杯期间不提供支持

**Comment by 1578339936** [comment]
词达人杯，我都不知道开始了，尴尬
